// examples/angular-test/src/app/app.component.ts
import { Component } from "@angular/core";
import { CardComponent } from "./components/card/card.component";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
  imports: [CardComponent],
})
export class AppComponent {
  title = "Angular + DOM Selector";
}

<main class="container">
  <header class="page-header">
    <h1>Angular + DOM Selector</h1>
    <p>
      按住 <kbd>⌘</kbd>（或 <kbd>Ctrl</kbd>）并点击任意元素，唤起源码弹窗。
    </p>
  </header>

  <app-card
    title="卡片 1"
    description="这是一个测试卡片。Command+点击这里试试。"
    buttonText="按钮 A"
  ></app-card>

  <app-card
    title="卡片 2"
    description="另一个测试卡片。"
    buttonText="按钮 B"
    variant="primary"
  ></app-card>
</main>

// examples/nextjs-test/app/page.tsx
import Header from "./components/Header";
import Card from "./components/Card";

export default function Home() {
  return (
    <main className="container">
      <Header />

      <Card
        title="卡片 1"
        description="这是一个测试卡片。Command+点击这里试试。"
        buttonText="按钮 A"
      />

      <Card
        title="卡片 2"
        description="另一个测试卡片。"
        buttonText="按钮 B"
        buttonVariant="primary"
      />
    </main>
  );
}
