// examples/nextjs-test/app/components/Card.tsx
export interface CardProps {
  title: string;
  description: string;
  buttonText: string;
  buttonVariant?: "primary";
}

export default function Card({ title, description, buttonText, buttonVariant }: CardProps) {
  return (
    <div className="card">
      <h2>{title}</h2>
      <p>{description}</p>
      <button className={buttonVariant ? `btn ${buttonVariant}` : "btn"}>
        {buttonText}
      </button>
    </div>
  );
}

// examples/angular-test/src/app/components/card/card.component.ts
import { Component, Input } from "@angular/core";

@Component({
  selector: "app-card",
  templateUrl: "./card.component.html",
  styleUrls: ["./card.component.css"],
})
export class CardComponent {
  @Input() title: string = "";
  @Input() description: string = "";
  @Input() buttonText: string = "";
  @Input() variant?: string;

  get btnClass(): string {
    return this.variant ? `btn ${this.variant}` : "btn";
  }
}

<div class="card">
  <h2>{{ title }}</h2>
  <p>{{ description }}</p>
  <button [class]="btnClass">{{ buttonText }}</button>
</div>
